Porting //eve/staging/2019-JENGU->//eve/development/MAINLINE at head (1601034) - using branchspec //eve/staging/2019-JENGU->//eve/development/MAINLINE
========================================

Change 1595198 by baldur@eve_mainline_BALDUR-WS on 2019/10/29 15:52:52

https://jira.ccpgames.com/browse/ENYA-236


Atmospheric audio for Concord Stellar Observatory

use wwise event: concord_observatory_loop_play

========================================

Change 1595225 by eric@eric_MAINLINE_FOR_REAL on 2019/10/29 16:12:15

[eve 2019-JENUG][audio] * Move aura warp drive active line to trigger right when a player chooses to warp.
* Wwise project changes for warp prep (remove ui sound, edit distortion a bit)
* soundbank generation.

https://jira.ccpgames.com/browse/TC-45

========================================

Change 1595882 by eric@eric_MAINLINE_FOR_REAL on 2019/10/30 12:30:30

[eve 2019-JENGU][audio] Bring daily_rewards_login_play from MAINLINE->2019-JENGU along with soundbank generation (which includes triglavian dreadnought sounds).

https://jira.ccpgames.com/browse/TFO-3364

========================================

Change 1598098 by baldur@eve_mainline_BALDUR-WS on 2019/11/01 13:13:36

[eve 2019-JENGU][audio] Trig Dreadnought - wwise soundbank generation

https://jira.ccpgames.com/browse/TC-24

========================================

Change 1600219 by joshua@joshua-ws on 2019/11/05 13:15:03

Staging Triglavian Dreadnought publish of 

Ship/Wreck/Explosion/Heatshader

https://jira.ccpgames.com/browse/TC-17

========================================

Change 1600273 by bara@eve_branches_staging_2019-JENGU_bara-pc on 2019/11/05 13:44:18

Implement: Integrated Seasonal Campaign UI for Rookie DLI
https://jira.ccpgames.com/browse/TFO-3287

 - put a frame around the navigation buttons and the 'x/y claimed' text
 - added a frame around the clone grade tracks

========================================

Change 1600282 by hjaltil@eve_branches_staging_2019-JENGU_hjaltil-pc on 2019/11/05 13:54:46

Text Overflow (Fitting Window) https://jira.ccpgames.com/browse/KOR-32

* Moved expand icon in defensePanel to the TOPLEFT, to avoid text clashing. Added animation to the icon to indicate feedback.
* Scaling the fitting window by the fontSizeFactor to avoid text clashing with the CPU/Power Grid and the main fitting circle
* Scaling the expandable menus by the fontSizeFactor to avoid container clipping.

========================================

Change 1600304 by arnarb@eve_branches_staging_2019-JENGU on 2019/11/05 14:03:00

Text Overflow (People & Places Window)
https://jira.ccpgames.com/browse/KOR-36

- Fixed alignment of text and made entry height dynamic

========================================

Change 1600367 by arnarb@eve_branches_staging_2019-JENGU on 2019/11/05 14:48:45

Text Overflow (Factional Warfare Window)
https://jira.ccpgames.com/browse/KOR-35

- Fixed alignment so that top container height is adjusted automatically

========================================

Change 1600399 by olafurth@eve_branches_staging_2019-JENGU_olafurth-pc on 2019/11/05 15:05:26

https://jira.ccpgames.com/browse/ENYA-247
Enabling the new travel system

========================================

Change 1600427 by arnarb@eve_branches_staging_2019-JENGU on 2019/11/05 15:20:37

Text Overflow (Ship Information > Traits Tab)
https://jira.ccpgames.com/browse/KOR-38

- left column width now increases in width with uicore.fontSizeFactor

========================================

Change 1600455 by olafurth@eve_branches_staging_2019-JENGU_olafurth-pc on 2019/11/05 15:31:24

Half way fixing the memory leak that occurs when we jump with the new system.
We are still leaking Tr2ObjectFollowCurveKeys

https://jira.ccpgames.com/browse/ENYA-246

========================================

Change 1600532 by danielp@eve_branches_staging_2019-JENGU_danielp-pc on 2019/11/05 16:09:04

Characters with too many bookmarks will receive no bookmarks at login due to dropped packet
https://jira.ccpgames.com/browse/EVEDEV-8709

Addressing both the server and client side part:
* Sending only max 20000 bookmarks to the client, to avoid exceeding the packet size limit.
* Displaying only 3000 bookmarks per group (subfolder or folder)
* Adding hints for folders, which are exceeding the limits.

========================================

Change 1600578 by baldur@eve_mainline_BALDUR-WS on 2019/11/05 16:45:03

https://jira.ccpgames.com/browse/TC-24

wwise work for remaining trig dread animations

========================================

Change 1600593 by eric@eric_MAINLINE_FOR_REAL on 2019/11/05 16:52:34

[eve 2019-JENGU][audio] Wwise edits for triglavian dreadnought.

https://jira.ccpgames.com/browse/TC-24

========================================

Change 1600608 by eric@eric_MAINLINE_FOR_REAL on 2019/11/05 16:58:57

[eve 2019-JENGU][audio] Soundbank generation for audio connected to tgdn01, cfu and tgfu06

https://jira.ccpgames.com/browse/TC-24
https://jira.ccpgames.com/browse/ENYA-238
https://jira.ccpgames.com/browse/ENYA-239

========================================

Change 1600887 by gregor@eve_branches_staging_2019-JENGU_gregor-pc on 2019/11/06 10:20:49

Removing "visibleTQ" and "visibleSerenity" from Firestorm SKINs to hide them in the Char Sheet

https://jira.ccpgames.com/browse/EVEDEV-8741

========================================

Change 1600975 by bara@eve_branches_staging_2019-JENGU_bara-pc on 2019/11/06 11:17:14

RuntimeError: Rookie campaigns are not enabled on this server
https://jira.ccpgames.com/browse/TQ-132918

 - this was not really a problem because if you didn't have access to the DLI then you didn't get there to set the setting that was causing the issue 
 - changed it so if the global config is off, we just don't bother going to the server and return None

========================================

Change 1601034 by hrafng@eve_branches_staging_2019-JENGU_hrafn-pc on 2019/11/06 12:40:50

Merging localization folder using //eve/sandbox/TEH-JENGU->//eve/staging/2019-JENGU

[git-p4: depot-paths = "//eve/branches/development/MAINLINE/carbon/src/Trinity/": change = 1601067]